/**
 * sarvamClient.js — Sarvam AI Text-to-Speech (TTS) Client
 * 
 * Sarvam is used EXCLUSIVELY for TTS (Text-to-Speech) in:
 *   - Podcast Generator (audio playback of scripts)
 *   - Socratic Voice Tutor (spoken AI responses)
 * 
 * This client calls Sarvam via a Vite dev proxy (/sarvam-api) to bypass
 * CORS restrictions, with full key rotation across all 9 Sarvam API keys.
 * 
 * Voice mapping for podcast speakers (bulbul:v3):
 *   - Host (Ria):    'kavya'  — Natural female voice
 *   - Expert (Kabir): 'anand' — Calm, authoritative male voice
 */

import { keyManager } from './keyManager';

// In dev: Vite proxy handles CORS (/sarvam-api → api.sarvam.ai)
// In prod: Express backend proxy handles it (/api/ai/tts-proxy → api.sarvam.ai)
const SARVAM_TTS_URL = import.meta.env.DEV
    ? '/sarvam-api/text-to-speech'
    : '/api/ai/tts-proxy';

// Voice configs for podcast speakers
const SPEAKER_VOICES = {
    host: { speaker: 'kavya', pace: 1.0, temperature: 0.5 },
    expert: { speaker: 'anand', pace: 1.0, temperature: 0.5 },
    questioner: { speaker: 'kavya', pace: 1.0, temperature: 0.5 },
    explainer: { speaker: 'anand', pace: 1.0, temperature: 0.5 },
    default: { speaker: 'kavya', pace: 1.0, temperature: 0.5 }
};

/**
 * Call Sarvam TTS API directly from browser.
 * Handles text chunking (2400 char limit) and multi-chunk concatenation.
 * @param {string} text - Text to convert to speech.
 * @param {Object} options - { speaker: 'questioner'|'explainer', target_language_code }
 * @returns {string} - Base64 audio data URL ready to play
 */
export async function callSarvamTTS(text, options = {}, _retryCount = 0) {
    const apiKey = keyManager.getKey('sarvam');
    if (!apiKey) throw new Error("No available Sarvam API keys.");

    // Resolve voice config
    const role = (options.speaker || 'explainer').toLowerCase();
    const voiceConfig = SPEAKER_VOICES[role] || SPEAKER_VOICES.default;

    // Sarvam has 2500 char limit — split at sentence boundaries
    const MAX_CHARS = 2400;
    const textChunks = [];

    if (text.length <= MAX_CHARS) {
        textChunks.push(text);
    } else {
        const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
        let currentChunk = '';
        for (const sentence of sentences) {
            if ((currentChunk + sentence).length > MAX_CHARS) {
                if (currentChunk) textChunks.push(currentChunk.trim());
                currentChunk = sentence;
            } else {
                currentChunk += sentence;
            }
        }
        if (currentChunk.trim()) textChunks.push(currentChunk.trim());
    }

    try {
        const audioChunks = [];

        for (let i = 0; i < textChunks.length; i++) {
            const payload = {
                inputs: [textChunks[i]],
                target_language_code: options.target_language_code ?? 'en-IN',
                speaker: voiceConfig.speaker,
                pace: voiceConfig.pace,
                model: 'bulbul:v3',
                speech_sample_rate: 22050,
                enable_preprocessing: true,
                temperature: voiceConfig.temperature || 0.5
            };

            const response = await fetch(SARVAM_TTS_URL, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'api-subscription-key': apiKey
                },
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                // Exhausted key — rotate and retry
                if (response.status === 429 || response.status === 403 || response.status === 402) {
                    keyManager.markKeyExhausted('sarvam');

                    if (_retryCount < 9) {
                        console.warn(`[Sarvam TTS] ${response.status}. Retrying with next key (${_retryCount + 1}/9)...`);
                        return callSarvamTTS(text, options, _retryCount + 1);
                    }
                }

                const errText = await response.text();
                console.error(`[Sarvam TTS] API Error ${response.status}:`, errText);
                throw new Error(`Sarvam TTS Error ${response.status}`);
            }

            const data = await response.json();
            if (data.audios && data.audios.length > 0) {
                audioChunks.push(data.audios[0]);
            }
        }

        if (audioChunks.length === 0) {
            throw new Error('No audio generated by Sarvam');
        }

        // Return as playable data URL (first chunk for now; multi-chunk can be handled by caller)
        const audioBase64 = audioChunks[0];
        return `data:audio/wav;base64,${audioBase64}`;

    } catch (err) {
        // On network error, try rotating key
        if (_retryCount < 9 && (err.message.includes('fetch') || err.message.includes('network'))) {
            keyManager.markKeyExhausted('sarvam');
            console.warn(`[Sarvam TTS] Network error, rotating key (${_retryCount + 1}/9)...`);
            return callSarvamTTS(text, options, _retryCount + 1);
        }
        throw err;
    }
}

export default callSarvamTTS;
